# BEGIN_KITTY_THEME
# OneDark-Pro
# include current-theme.conf
# END_KITTY_THEME

# include ~/.cache/wal/colors-kitty.conf

include OneDark-Pro.conf

# color2 #076E0F
# color2 #8e48a8

font_family      JetBrainsMono Nerd Font Mono
bold_font        JetBrainsMono Nerd Font Mono Extra Bold
bold_italic_font JetBrainsMono Nerd Font Mono Extra Bold Italic

font_size 10.0

# tab_bar_style powerline
# tab_powerline_style round
# active_tab_foreground #ffffff
# active_tab_background #333333

# # Tab bar
# # tab_bar_min_tabs 1
# tab_bar_edge bottom
# tab_bar_style powerline
# tab_powerline_style slanted
# tab_title_template {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
# # Ends Tab bar

# Tab
tab_powerline_style         round
tab_bar_style               powerline
tab_bar_edge                bottom
tab_title_template          " {'󰊠 ' if (index % 2) == 0 else '󰆘 '}{fmt.bold}{sup.index}{title}"
active_tab_title_template   " 󰮯 {fmt.nobold}{sup.index}{title}"

# Nerd Fonts v2.3.3
symbol_map U+23FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A3,U+E0B0-U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6AA,U+E700-U+E7C5,U+EA60-U+EBEB,U+F000-U+F2E0,U+F300-U+F32F,U+F400-U+F4A9,U+F500-U+F8FF,U+F0001-U+F1AF0 Symbols Nerd Font

strip_trailing_spaces smart

remember_window_size  no
initial_window_width  960
initial_window_height 540

draw_minimal_borders yes

editor nvim
allow_hyperlinks yes
enable_audio_bell no
# background_opacity 0.85

scrollback_pager_history_size 0
scrollback_lines 100000

shell_integration no-cursor
mouse_hide_wait 3

enabled_layouts splits

allow_remote_control socket-only
listen_on unix:/tmp/kitty
shell_integration enabled

shell_integration no-sudo

# kitty-scrollback.nvim Kitten alias
action_alias kitty_scrollback_nvim kitten /home/carlos/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py

# Browse scrollback buffer in nvim
map kitty_mod+h kitty_scrollback_nvim
# Browse output of the last shell command in nvim
map kitty_mod+g kitty_scrollback_nvim --config ksb_builtin_last_cmd_output
# Show clicked command output in nvim
mouse_map ctrl+shift+right press ungrabbed combine : mouse_select_command_output : kitty_scrollback_nvim --config ksb_builtin_last_visited_cmd_output

# Open splits in the current working directory
map ctrl+shift+8 launch --cwd=current --location=hsplit
map ctrl+shift+9 launch --cwd=current --location=vsplit

# Open splits in home directory
map ctrl+shift+alt+8 launch --location=hsplit
map ctrl+shift+alt+9 launch --location=vsplit

# map ctrl+shift+h shell kitty @ focus-window --direction=left
# map ctrl+shift+l shell kitty @ focus-window --direction=right
# map ctrl+shift+k shell kitty @ focus-window --direction=top
# map ctrl+shift+j shell kitty @ focus-window --direction=bottom

# Open tab in the current working directory
map ctrl+shift+t new_tab_with_cwd
# Open tab in home directory
map ctrl+shift+y new_tab
# map ctrl+shift+home launch --location=vsplit

# Switch focus to the neighboring window in the indicated direction
map ctrl+alt+h neighboring_window left
map ctrl+alt+l neighboring_window right
map ctrl+alt+k neighboring_window up
map ctrl+alt+j neighboring_window down

map ctrl+shift+j move_tab_forward
map ctrl+shift+k move_tab_backward
